name: social_tripper_mobile
description: "A new Flutter project."

# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  appinio_video_player: ^1.2.2
  #  better_open_file: ^3.6.5
  cached_video_player: 2.0.4
  camerawesome: 2.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.0
  flutter_foreground_task: 8.14.0
  flutter_map: ^7.0.2
  get_thumbnail_video: ^0.7.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  path_provider: ^2.1.4
  photo_view: 0.15.0
  sensors_plus: ^6.0.1
  url_launcher: ^6.1.2
  video_player: ^2.6.0
  rive: ^0.7.0
  flutter_svg: ^2.0.15
  flutter_bloc: ^8.1.6
  tuple: ^2.0.0
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo_animation.riv
    - assets/icons/
    - assets/MediaFiles/
    - assets/flags/
    - assets/countries/
    - assets/activities/

  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Thin.ttf
          weight: 100
        - asset: fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: fonts/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit-Regular.ttf
          weight: 400
        - asset: fonts/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: fonts/Kanit-Bold.ttf
          weight: 700
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSans3-Light.ttf
          weight: 300
        - asset: fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: fonts/SourceSans3-Medium.ttf
          weight: 500
        - asset: fonts/SourceSans3-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSans3-Bold.ttf
          weight: 700
